CC=gcc-15
INCLUDE=include
LIB=lib
CFLAGS=-I$(INCLUDE) -fms-extensions $$(pkg-config --cflags --libs gsl sdl2 sdl2_image sdl2_mixer)

# Marigold
MARIGOLD_INCLUDE=$(INCLUDE)/marigold
MARIGOLD_MODULES=$(MARIGOLD_INCLUDE)/modules
MARIGOLD_LIB=$(LIB)/marigold

MARIGOLD_ENTITIES_I=$(MARIGOLD_MODULES)/entities.c
MARIGOLD_ENTITIES_H=$(MARIGOLD_MODULES)/entities.h
MARIGOLD_ENTITIES_O=$(MARIGOLD_LIB)/entities.o

MARIGOLD_LEVEL_I=$(MARIGOLD_MODULES)/level.c
MARIGOLD_LEVEL_H=$(MARIGOLD_MODULES)/level.h
MARIGOLD_LEVEL_O=$(MARIGOLD_LIB)/level.o

MARIGOLD_RENDERER_I=$(MARIGOLD_MODULES)/renderer.c
MARIGOLD_RENDERER_H=$(MARIGOLD_MODULES)/renderer.h
MARIGOLD_RENDERER_O=$(MARIGOLD_LIB)/renderer.o

MARIGOLD_MODULES_I=$(MARIGOLD_ENTITIES_I) \
				   $(MARIGOLD_LEVEL_I) 	  \
				   $(MARIGOLD_RENDERER_I) \
				   $(MARIGOLD_ENTITIES_H) \
				   $(MARIGOLD_LEVEL_H)    \
				   $(MARIGOLD_RENDERER_H)

MARIGOLD_MODULES_O=$(MARIGOLD_ENTITIES_O) \
				   $(MARIGOLD_LEVEL_O)    \
				   $(MARIGOLD_RENDERER_O)

MARIGOLD_I=$(MARIGOLD_INCLUDE)/marigold.c
MARIGOLD_H=$(MARIGOLD_INCLUDE)/marigold.h
MARIGOLD_O=$(MARIGOLD_LIB)/marigold.o

# microui
MICROUI_INCLUDE=$(INCLUDE)/microui
MICROUI_LIB=$(LIB)/microui

MICROUI_I=$(MICROUI_INCLUDE)/microui.c
MICROUI_H=$(MICROUI_INCLUDE)/microui.h
MICROUI_O=$(MICROUI_LIB)/microui.o

# lib
LIB_I=$(MARIGOLD_I) \
	  $(MICROUI_I)  \
	  $(MARIGOLD_H) \
	  $(MICROUI_H)

LIB_O=$(MARIGOLD_O) \
	  $(MICROUI_O)

# main
MAIN_I=main.c
MAIN_O=$(LIB)/main.o

# Link
LINK_I=$(MARIGOLD_MODULES_O) \
	   $(LIB_O)              \
	   $(MAIN_O)

LINK_O=main

# Targets
all: $(LINK_I) $(LINK_O)

$(MARIGOLD_MODULES_O): $(MARIGOLD_MODULES_I)
	$(CC) $(MARIGOLD_ENTITIES_I) -c -o $(MARIGOLD_ENTITIES_O) $(CFLAGS)
	$(CC) $(MARIGOLD_LEVEL_I) -c -o $(MARIGOLD_LEVEL_O) $(CFLAGS)
	$(CC) $(MARIGOLD_RENDERER_I) -c -o $(MARIGOLD_RENDERER_O) $(CFLAGS)

$(LIB_O): $(LIB_I)
	$(CC) $(MARIGOLD_I) -c -o $(MARIGOLD_O) $(CFLAGS)
	$(CC) $(MICROUI_I) -c -o $(MICROUI_O) $(CFLAGS)

$(MAIN_O): $(MAIN_I)
	$(CC) $(MAIN_I) -c -o $(MAIN_O) $(CFLAGS)

$(LINK_O): $(LINK_I)
	$(CC) $(LINK_I) -o $(LINK_O) $(CFLAGS)

clean:
	trash $(LINK_I) $(LINK_O)

